name: Python Action

on:
  issues:
    types: [opened]
    tags:
      - hey-noah
  issue_comment:
    types: [created]

jobs:
  run-python:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'hey-noah')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.issue.labels.*.name, 'hey-noah'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git config --global credential.helper store
      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install openai
          echo "${{ github.event.issue.body }}" > input.txt
          new_branch_name=$(python bot/main.py "$(cat input.txt)")
          git push -u origin "$new_branch_name"
          gh pr create --title "Added new file to branch" --body "Please review and merge this pull request" --head $new_branch_name --base main
